བསྐྱར་བཟོ།
Esukhia/derge-kangyur-old pull request #14
Opened 2018-09-10 11:14 UTC by tashikuncok

2018-09-16 09:13 UTC, ngawangtrinley commented on derge-kangyur-tags/001-tagged.txt
> +[264b.1]སྐུ་མ་མཐོང་བས། མཁན་པོ་བཅོམ་ལྡན་འདས་ཀྱི་གཟུགས་ཀྱི་སྐུ་ལྟར་མཆིའོ། །བུ་དེ་བཞིན་དུ་གྱིས་ཤིག །དེ་བཞིན་གཤེགས་པ་དགྲ་བཅོམ་པ་ཡང་དག་པར་རྫོགས་པའི་སངས་རྒྱས་མཐོང་བ་ནི་རྙེད་པར་དཀའ་སྟེ། དཔེར་ན་མེ་ཏོག་་དུམ་བ
ཨུ་ཆད།

2018-10-21 13:32 UTC, rekongrabten requested changes
འདི་དག་ལ་ཞིབ་ནན་གྱིས་གཟིགས་རོགས།

2018-10-21 13:32 UTC, rekongrabten commented on derge-kangyur-tags/068-tagged.txt
> +[225b.1]མཆིན་པ། མཆིན་པའི་འོག་ཏུ་(མཆེར་པ,མཚེར)། (མཆེར་,མཚེར་)པའི་འོག་ཏུ་རྒྱུ་མ། རྒྱུ་མའི་འོག་ཏུ་གཉེ་མ། གཉེ་མའི་འོག་ཏུ་མདོམས། མདོམས་ཀྱི་འོག་ཏུ་ཕོ་མཚན། ཕོ་མཚན་གྱི་འོག་ཏུ་བརླ། བརླའི་འོག་ཏུ་པུས་མོའི་ལྷ་ང་
འདིར་དོགས་རྟགས་བཀོད་སྟངས་ནོར་འདུག

2018-10-21 13:32 UTC, rekongrabten commented on derge-kangyur-tags/092-tagged.txt
> +[179a.6]བི་ཤུདྡྷ་པི་ཥ་ཡ། ནི་བཱ་སི་ན། མ་ཧཱ་ཀཱ་རུ་ཎི་ཀཱ། ཤྭེ་ཏ་ཡཛྙོ་པ་བཱི་ཏ་རཏྣ་མ་ཀུ་ཊ་མཱ་ལཱ་དྷ་ར། སརྦ་ཛྙཱ་ཤི་ར་སི་ཀྲྀ་ཏ་མ་ཀུ་ཊ་མ་ཧདྦྷུཏཿ་ཀ་མ་ལཱ་ལཾ་ཀྲྀ་ཏ། ཀ་ར་ཏ་ལ། དྷྱཱ་ན་ས་མཱ་དྷི། བི་མོ་ཀྵ་པྲ་ཀམྤ། བ་ཧ
ཏཿཀ འདི་གཉིས་ཀྱི་བར་དུ་ཚེག་མི་དགོས།

2018-10-21 13:32 UTC, rekongrabten commented on derge-kangyur-tags/102-tagged.txt
> +[135b.2]བསྡུས་པའི་རྒྱུད་ཀྱི་རྒྱལ་པོ་དུས་ཀྱི་འཁོར་ལོའི་འགྲེལ་བཤད་རྩ་བའི་རྒྱུད་ཀྱི་རྗེས་སུ་འཇུག་པ་སྟོང་ཕྲག་བཅུ་གཉིས་པ་དྲི་མ་མེད་པའི་འོད་ལས་ཀུན་འབྱུང་གི་བདེན་པ་ལ་སོགས་པའི་།། །།ད་ནི་འཁོར་ལོ་ཅན་ཞེས་པ་ལ་སོ
འདིར་ཡི་གེ་དུམ་ཚན་ཞིག་གསུབ་འདུག

2018-11-02 01:24 UTC, rekongrabten requested changes
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-02 01:24 UTC, rekongrabten commented on derge-kangyur-tags/102-tagged.txt
> +[372b.4]ཨོཾ་བཛྲ་གཱ་ཏྲ་ཧཾ་བཛྲེ་ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་ཀརྐ་ཊ་ལའོ། །ཨོཾ་བཛྲ་ནེ་ཏྲ་ཨཾ་བཛྲེ་[ཪྻ་]ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་སེང་གེ་ལའོ། །ཨོཾ་བཛྲ་ཤྲོ་ཏྲ་ཧཱ་བཛྲེ་ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་བུ་མོའི་འཕོ་བ་ལའོ། །ཨོཾ་བཛྲ་[གྷྲཱ་]ཎ་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-03 00:09 UTC, rekongrabten requested changes
འདི་གཅིག་པོ་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-03 00:09 UTC, rekongrabten commented on derge-kangyur-tags/098-tagged.txt
> +[268b.5]དེ་ལ་སྨོད་པ་ནི། །དཔེརན་ན་མུན་ཁུང་སྒྲོན་བསད་ན། །མཐོང་བའི་དོན་ནི་མི་རྟོགས་བཞིན། །སྡུག་བསྔལ་ཉམ་ཐག་ཡུན་རིངས་སུ། །བསྐལ་པ་མང་པོར་མྱོང་བར་མངོན། །དེ་བས་དེ་ལ་གུས་པ་རྟག་ཏུ་གྱིས། །ལུས་ལ་དབང་བའི་རྒྱལ་པོ་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-03 00:31 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2018-11-2

2018-11-03 00:31 UTC, rekongrabten commented on derge-kangyur-tags/016-tagged.txt
> +[130a.1]འདོད་པ་རྣམས་ལ་ནི་འཚོ་བ་བྱིན། ཡོ་བྱད་འདོད་པ་རྣམས་ལ་ནི་ཡོ་བྱད་བྱིན། ནད་ཀྱི་རྐྱེན་རྩི་དང་ཡོ་བྱད་འདོད་པ་རྣམས་ལ་ནི། ནད་ཀྱི་རྐྱེན་རྩི་དང་ཡོ་བྱད་བྱིན། ནོར་བུ་དང་། མུ་ཏིག་དང་། བཻཌཱུཪྻ་དང་། དུང་དང་། མ
འདི་མ་དཔེར་བཻ་ཌཱུཪྻ འདི་ལྟར་གསལ་བས་ཚེག་འཇོག་རོགས།

2018-11-03 00:31 UTC, rekongrabten commented on derge-kangyur-tags/076-tagged.txt
> +[283a.7]ཕྱོགས་བཞིའི་སྐྱེ་བོ་མང་པོས་དཔལ་འབར་མང་པོ་ཁྱེར་ཏེ་དེ་ལས་སྦར་ཏེ་བཟའ་བཅའ་དག་{འཆེད་མཆོད་}པར་བྱེད། མུན་པ་དག་སེལ་བར་བྱས་ཀྱང་མེ་དེ་ཟད་པར་མི་འགྱུར་བ་ལྟར་བསོད་ནམས་ཀྱི་ཕུང་པོ་དེ་ཡང་དེ་བཞིན་ནོ། །ཡང་བཅོམ
རྟགས་འདི་གང་ཡིན་ནམ།

2018-11-03 00:31 UTC, rekongrabten commented on derge-kangyur-tags/083-tagged.txt
> +[216b.2]དང་ཁ་དོག་འདྲ་བ་ལ་གྲི་གུག་དང་ཐོད་པ་ཅན་ཕྱག་རྒྱ་ལྔས་རྣམ་པར་བརྒྱན་པའི་ལུས་ཅན་མར་བརྩོན་པའི་སེམས་ཀྱིས་བསྒོམ་པར་བྱ་ཞིང་། དེ་ནས་ང་རྒྱལ་བྱས་ན་བདག་ཉིད་གྲུབ་པར་འགྱུར་བར་ཐེ་ཙོམ་མེད་དོ། །དེ་ནས་བཛྲ་སྭ་བྷཱ་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། ཨཱཏྨ་ཀོ྅ཧཾ་གིས་ཞེས་བཟོ་དགོས།

2018-11-03 00:31 UTC, rekongrabten commented on derge-kangyur-tags/092-tagged.txt
> +[167b.5]བྷི་ཥིཉྩ་ཡ། མ་མ་སརྦ་ཏ་ཐཱ་ག་ཏ་ཨ་བྷི་ཥེ་ཀ་མ་ཎི་མ་ཎི་སྭཱ་ཧཱ། དབང་བསྐུར་བའི་སྔགས་སོ། །ཨོཾ་ཨ་མོ་གྷ་པདྨ་བ་སུན་དྷ་ར། དྷ་ར་དྷ་ར། དྷ་ར་ཎི། ཧཱུྃ། སྟན་གྱི་གསང་སྔགས་སོ། །ཨོཾ་ཨ་མོ་གྷ་ས་མནྟ་པརྱ་ང་ཀེ །བྷུ་བ
འདི་མཎྜེ་གསུབ་ནོར་ཤོར་འདུག

2018-11-03 00:31 UTC, rekongrabten commented on derge-kangyur-tags/092-tagged.txt
> +[179a.6]བི་ཤུདྡྷ་པི་ཥ་ཡ། ནི་བཱ་སི་ན། མ་ཧཱ་ཀཱ་རུ་ཎི་ཀཱ། ཤྭེ་ཏ་ཡཛྙོ་པ་བཱི་ཏ་རཏྣ་མ་ཀུ་ཊ་མཱ་ལཱ་དྷ་ར། སརྦ་ཛྙཱ་ཤི་ར་སི་ཀྲྀ་ཏ་མ་ཀུ་ཊ་མ་ཧདྦྷུཏཿ་ཀ་མ་ལཱ་ལཾ་ཀྲྀ་ཏ། ཀ་ར་ཏ་ལ། དྷྱཱ་ན་ས་མཱ་དྷི། བི་མོ་ཀྵ་པྲ་ཀམྤ། བ་ཧ
འདིའི་རྣམ་བཅད་ཀྱི་རྒྱབ་ལ་ཚེག་མེད།

2018-11-03 00:31 UTC, rekongrabten commented on derge-kangyur-tags/102-tagged.txt
> +[372b.4]ཨོཾ་བཛྲ་གཱ་ཏྲ་ཧཾ་བཛྲེ་ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་ཀརྐ་ཊ་ལའོ། །ཨོཾ་བཛྲ་ནེ་ཏྲ་ཨཾ་བཛྲེ་[ཪྻ་]ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་སེང་གེ་ལའོ། །ཨོཾ་བཛྲ་ཤྲོ་ཏྲ་ཧཱ་བཛྲེ་ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་བུ་མོའི་འཕོ་བ་ལའོ། །ཨོཾ་བཛྲ་[གྷྲཱ་]ཎ་
འདིའི་རྟགས་གཉིས་དེ་སེལ་རོགས།

2018-11-08 14:18 UTC, rekongrabten requested changes
འདི་གཅིག་པུ་བསྐྱར་དུ་བཟོ་རོགས།

2018-11-08 14:18 UTC, rekongrabten commented on derge-kangyur-tags/063-tagged.txt
> +[108b.7]གིས་ཐར་པ་ཡོད་པ་ཉིད་དུ་གསུངས་སོ། །གསོལ་པ། གལ་ཏེ་ཐར་པ་ཐོབ་པ་བསྟན་པ་དང་། དབང་ཕྱུག་ལགས་ན་སེམས་ཅན་ཡང་མཆིས་ཤིང་བརྟན་པར་རིག་པར་བགྱི་ལགས་སོ། །དེ་ཅིའི་སླད་དུ་ཞེ་ན། དུ་བས་ཞུག་བཞིན་དུ་གལ་ཏེ་ཐར་པ་ཐེར་ཟུག
འདིའི་ཞུག་དེ་ཞུགས་ཞེས་བཟོ་རོགས།

2018-11-13 02:52 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་དགོས་པ་དང་ད་དུང་སྔོན་གྱི་དཀའ་ངལ་ཁ་ཤས་ལྷག་འདུག་པས་དེ་དག་ཀྱང་མཉམ་དུ་བཟོ་རོགས།

2018-11-13 02:52 UTC, rekongrabten commented on derge-kangyur-tags/042-tagged.txt
> +[125a.6]པ་དེ་ནི་ཐོབ་པ་ཡང་མ་ཡིན། ཆུད་ཟོས་པ་ཡང་མ་ཡིན་ནོ་ཞེས་བྱ་བར་རབ་ཏུ་ཤེས་སོ། །ཀུན་ཏུ་རྒྱུ་དག་དེ་ལྟར་ན་དེ་ནི་ཆོས་ཐམས་ཅད་ཀྱི་ཆོས་ཉིད་དོ། །ཆོས་ཉིད་གང་གིས་ཆོས་ཐམས་ཅད་དེ་བཞིན་ཉིད་མ་ནོར་བ་དེ་བཞིན་ཉིད། གཞན
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-13 02:52 UTC, rekongrabten commented on derge-kangyur-tags/071-tagged.txt
> +[204a.3]མེའི་གོང་བུ་རྩ་བརྒྱད་འདྲ་བ་རྣམས་ཡིན་ནོ། །རི་རྣམ་པ་དུ་མ་དང་ཤིང་གི་རིགས་གཞན་དག་རྣམས་དང་། པད་མའི་རིགས་རྣམས་དང་། སྐྱེད་མོས་ཚལ་གྱི་རིགས་རྣམས་དང་། རི་དགས་ཀྱི་རིགས་རྣམས་དང་། རིའི་རྩེ་མོའི་རིགས་རྣམ་པ
འདི་གཙང་མ་བཟོ་རོགས།

2018-11-13 02:52 UTC, rekongrabten commented on derge-kangyur-tags/076-tagged.txt
> +[283a.7]ཕྱོགས་བཞིའི་སྐྱེ་བོ་མང་པོས་དཔལ་འབར་མང་པོ་ཁྱེར་ཏེ་དེ་ལས་སྦར་ཏེ་བཟའ་བཅའ་དག་{འཆེད་མཆོད་}པར་བྱེད། མུན་པ་དག་སེལ་བར་བྱས་ཀྱང་མེ་དེ་ཟད་པར་མི་འགྱུར་བ་ལྟར་བསོད་ནམས་ཀྱི་ཕུང་པོ་དེ་ཡང་དེ་བཞིན་ནོ། །ཡང་བཅོམ
འདི་ལ་འཚེད་ཅེས་བྲིས་ན་འགྲིག

2018-11-14 11:23 UTC, tashikuncok commented on derge-kangyur-tags/102-tagged.txt
> +[372b.4]ཨོཾ་བཛྲ་གཱ་ཏྲ་ཧཾ་བཛྲེ་ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་ཀརྐ་ཊ་ལའོ། །ཨོཾ་བཛྲ་ནེ་ཏྲ་ཨཾ་བཛྲེ་[ཪྻ་]ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་སེང་གེ་ལའོ། །ཨོཾ་བཛྲ་ཤྲོ་ཏྲ་ཧཱ་བཛྲེ་ཧཱུཾ་ཧཱུྃ་ཕཊ་ཅེས་པ་བུ་མོའི་འཕོ་བ་ལའོ། །ཨོཾ་བཛྲ་[གྷྲཱ་]ཎ་
བསྐྱར་བཟོ་བྱས་ཚར་ཡིན།

2018-11-27 11:27 UTC, merged