དེ་རིང་ལས་ཀ
Esukhia/derge-kangyur-old pull request #16
Opened 2018-10-15 11:26 UTC by rinzin59

2018-10-19 15:31 UTC, rekongrabten approved these changes

2018-10-19 15:34 UTC, rekongrabten requested changes

2018-10-19 15:34 UTC, rekongrabten commented on derge-kangyur-tags/007-tagged.txt
> +[25b.6]ལྟུང་བ་མེད་དོ། །གདིང་བའི་ལྟུང་བྱེད་དེ་(བཅྭ་,བཅྭོ་)ལྔ་པ་རྫོགས་སོ།། །།སངས་རྒྱས་བཅོམ་ལྡན་འདས་མཉན་ཡོད་ན་རྒྱལ་བྱེད་ཀྱི་ཚལ་མགོན་མེད་ཟས་སྦྱིན་གྱི་ཀུན་དགའ་ར་བ་ན་བཞུགས་སོ། །དེའི་ཚེ་ན་ཚེ་དང་ལྡན་པ་འཆར་ཀས
འདི་ལ་དོགས་མ་བརྒྱབས་ཀྱང་ཆོག་མོད། རྒྱག་གཔ་ཡིན་ན་(བཅྭ་,བཅོ་) འདི་ལྟར་བཀོད་དགོས།

2018-10-19 15:34 UTC, rekongrabten commented on derge-kangyur-tags/002-tagged.txt
> +[294b.6]ཏོ། །ལྟེང་རྒྱས་དང་། ཆུ་ཀླུང་དང་། ག་ཡཱ་འོད་སྲུང་རྣམས་ཀྱི་ལེའུ་སྟེ་(བཅྭ་,བཅྭོ་)་ལྔ་པའོ།། །།དེ་ནས་དགེ་སློང་གནས་བརྟན་གནས་བརྟན་རྣམས་ཀྱིས་ཚེ་དང་ལྡན་པ་གྲགས་པ་ལ་འདི་སྐད་ཅེས་སྨྲས་སོ། །ཚེ་དང་ལྡན་པ་གྲགས
འདི་ལ་དོགས་མ་བརྒྱབས་ཀྱང་ཆོག་མོད། རྒྱག་གཔ་ཡིན་ན་(བཅྭ་,བཅོ་) འདི་ལྟར་བཀོད་དགོས།

2018-10-19 15:34 UTC, rekongrabten commented on derge-kangyur-tags/014-tagged.txt
> +[326a.3]སྙིང་རྗེ་ཆེན་པོ་དེས་རློམ་སེམས་སུ་མི་བྱའོ། །སངས་རྒྱས་ཀྱི་ཆོས་མ་འདྲེས་པ་་བརྒྱད་ཤེས་པར་བྱ་སྟེ། སངས་རྒྱས་ཀྱི་ཆོས་མ་འདྲེས་པ་བཅྭོ་བརྒྱད་པོ་དེ་དག་གིས་རློམ་སེམས་སུ་མྱི་བྱའོ། །ཚེ་དང་ལྡན་པ་ཤ་ར་དྭ་ཏིའི་
འདི་བཟོ་ནོས་ཤོར་འདུག

2018-10-19 15:37 UTC, rekongrabten requested changes

2018-10-19 15:37 UTC, rekongrabten commented on derge-kangyur-tags/013-tagged.txt
> +[278b.4]གང་ཞེ་ན། བསམས་བཞིན་ཆོས་མ་ཡིན་པའི་ཕྱོགས་ལས་ཆོས་ཀྱི་ཕྱོགས་སུ་འོངས་པ་སྟེ། དེ་ལྟར་ན་བདག་ཉིད་ཀྱིས་བདག་ཉིད་ལྷན་ཅིག་ཏུ་གནས་པར་བྱེད་པའོ། །དགེ་འདུན་གྱིས་ཆོས་བཞིན་དུ་བྱས་པ་གང་ཞེ་ན། དགེ་འདུན་གྱིས་མི་(བས
འདིའི་དོན་གང་ཡིན་ནམ།

2018-10-19 15:37 UTC, rekongrabten commented on derge-kangyur-tags/038-tagged.txt
> +[334a.7]དེ་བཞིན་གཤེགས་པའི་སྐུ་གཟུགས། མྱི་ཆེན་པོའི་མཚན་སུམ་ཅུ་རྩ་གཉིས་ཀྱིས་བརྒྱན་པ་སྐྱིལ་མོ་ཀྲུང་དུ་བཅས་ཏེ་བཞུགས་པ་དག་ཀྱང་མཐོང་ངོ་། །ས་ཆེན་པོའི་གཞི་བཻ་ཌཱུ་རྱ་ལས་གྲུབ་པ། མྱིག་མངས་རིས་སུ་འདུག་པའི་མྱིག་མ
འདི་ལ་ཡང་བསྐྱར་གཟིགས་རོགས།

2018-10-19 15:37 UTC, rekongrabten commented on derge-kangyur-tags/038-tagged.txt
> +[337b.5]ལས་ཇི་ལྟ་བུར་བྱས་ཤིང་བསགས་པའི་རྣམ་པར་སྨིན་པས། ལས་མི་དགེ་བའི་རྐྱེན་གྱིས་ནི། སེམས་ཅན་དམྱལ་བ་དང་། བྱོལ་སོང་གི་སྐྱེ་གནས་དང་། ཡི་དགས་ཀྱི་ཡུལ་ལམ། གཤིན་རྗེའི་མྱི་ལག་ཆ་གཉེ་མས་པ་ཐོགས་པ། གཤེ་ཞིང་
འདི་ལ་ཡང་བསྐྱར་གཟིགས་རོགས།

2018-10-19 15:37 UTC, rekongrabten commented on derge-kangyur-tags/080-tagged.txt
> +[320a.7]དག་གནས། །ང་ནི་སྐྱེ་དང་འཆི་བའང་ང་། །ང་ནི་ནད་དང་རྒས་པའང་ང་། །ང་ནི་བསོད་ནམས་སྡིག་པའང་ང་། །དེ་ཡི་ལས་ཀྱི་འབྲས་ཉིད་ང་། །འགྲོ་ཀུན་རང་བཞིན་སངས་རྒྱས་ཉིད། །ཀུན་དུ་བདག་གི་གཟུགས་ཉིད་འདི། །རྣལ་འབྱོར་དེ་ཉི
འདི་ལ་ཡང་བསྐྱར་གཟིགས་རོགས།

2018-10-20 11:17 UTC, rinzin59 commented
2018-10-20

2018-10-21 13:26 UTC, rekongrabten requested changes
འདི་དག་ལ་ཞིབ་ནན་གྱིས་གཟིགས་རོགས།

2018-10-22 10:54 UTC, rinzin59 commented on derge-kangyur-tags/080-tagged.txt
> +[320a.7]དག་གནས། །ང་ནི་སྐྱེ་དང་འཆི་བའང་ང་། །ང་ནི་ནད་དང་རྒས་པའང་ང་། །ང་ནི་བསོད་ནམས་སྡིག་པའང་ང་། །དེ་ཡི་ལས་ཀྱི་འབྲས་ཉིད་ང་། །འགྲོ་ཀུན་རང་བཞིན་སངས་རྒྱས་ཉིད། །ཀུན་དུ་བདག་གི་གཟུགས་ཉིད་འདི། །རྣལ་འབྱོར་དེ་ཉི
མ་དཔེ་ནང་ལ་འདི་(པའང་ང་)འདྲ་འདུག

2018-10-22 10:56 UTC, rinzin59 commented on derge-kangyur-tags/080-tagged.txt
> +[320a.7]དག་གནས། །ང་ནི་སྐྱེ་དང་འཆི་བའང་ང་། །ང་ནི་ནད་དང་རྒས་པའང་ང་། །ང་ནི་བསོད་ནམས་སྡིག་པའང་ང་། །དེ་ཡི་ལས་ཀྱི་འབྲས་ཉིད་ང་། །འགྲོ་ཀུན་རང་བཞིན་སངས་རྒྱས་ཉིད། །ཀུན་དུ་བདག་གི་གཟུགས་ཉིད་འདི། །རྣལ་འབྱོར་དེ་ཉི
མ་དཔེ་ནང་ལ་འདི་(པའང་ང་)འདྲ་འདུག

2018-11-29 09:00 UTC, merged