ནང་འདྲེན།
Esukhia/derge-kangyur-old pull request #18
Opened 2018-10-23 11:26 UTC by tibetanboy

2018-10-29 11:24 UTC, tibetanboy commented
ཞུ་དག་བཏང་ཡོད།

2018-11-02 01:20 UTC, rekongrabten requested changes
འདི་དག་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-02 01:20 UTC, rekongrabten commented on derge-kangyur-tags/068-tagged.txt
> +[249b.4]མ་འཇིག་བྱེད་ལ་རླུང་འོག་ཏུ་འགྲོས་གནོད་པར་བྱེད་དོ། །སྲིན་བུ་{དཔོས}་བྱེད་ལ་རླུང་གྱེན་དུ་འགྲོས་གནོད་པར་བྱེད་དོ། །སྲིན་བུ་མདོག་བཟང་ལ་རླུང་ངོས་ལྡང་གིས་གནོད་པར་བྱེད་དོ། །སྲིན་བུ་གཞང་རྐང་ལ་རླུང་མིད་པ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-02 01:20 UTC, rekongrabten commented on derge-kangyur-tags/072-tagged.txt
> +[213b.5]བརྗོད་པ་ཡིན། །དགེ་སློང་བག་ཡོད་ལ་དགའ་ཞིང་། །བག་མེད་པ་ལ་འཇིགས་ལྟ་བས། །བདག་ཉིད་ངན་འགྲོ་ལས་{འདྲེལ}་ཏེ། །འདམ་རྫབ་ལས་ནི་གླང་ཆེན་བཞིན། །དགེ་སློང་བག་ཡོད་ལ་དགའ་ཞིང་། །བག་མེད་པ་ལ་འཇིགས་ལྟ་བས། །སྡིག་པའི
འདི་ལ་གཟིགས་རོགས།

2018-11-02 01:20 UTC, rekongrabten commented on derge-kangyur-tags/079-tagged.txt
> +[45b.5]སངས་རྒྱས་ལ་སོགས་མུ་སྟེགས་ཀུན། །ལྷ་མིན་གནོད་སྦྱིན་སྲིན་པོ་དང་། །དེ་ཉིད་འདོད་ཆགས་ཆགས་བྲལ་དང་། །འདོད་པས་ཐར་བར་གྱུར་པ་ཉིད། །དེ་ཉིད་བུད་མེད་རྣམས་ལ་ཆགས། །དེ་ཉིད་མངལ་ནི་རབ་ཏུ་ལེན། །དེ་ཉིད་འཆི་སྟེ་རིལ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-03 00:05 UTC, rekongrabten requested changes

2018-11-03 00:05 UTC, rekongrabten commented on derge-kangyur-tags/079-tagged.txt
> +[45b.5]སངས་རྒྱས་ལ་སོགས་མུ་སྟེགས་ཀུན། །ལྷ་མིན་གནོད་སྦྱིན་སྲིན་པོ་དང་། །དེ་ཉིད་འདོད་ཆགས་ཆགས་བྲལ་དང་། །འདོད་པས་ཐར་བར་གྱུར་པ་ཉིད། །དེ་ཉིད་བུད་མེད་རྣམས་ལ་ཆགས། །དེ་ཉིད་མངལ་ནི་རབ་ཏུ་ལེན། །དེ་ཉིད་འཆི་སྟེ་རིལ
འདི་བསྐྱར་དུ་བཟོ་རོགས། པོའི་གནས་གཉིས་ཀྱི་བར་དུ་ཚེག་ཆད་འདུག

2018-11-03 00:06 UTC, rekongrabten approved these changes

2018-11-03 00:06 UTC, merged