ནང་འདྲེན
Esukhia/derge-kangyur-old pull request #37
Opened 2018-11-14 03:30 UTC by gyamtso59

2018-11-14 22:43 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-14 22:43 UTC, rekongrabten commented on derge-kangyur-tags/080-tagged.txt
> +[232b.4]ནི། །བརྟན་ཞིང་རྟག་པའི་ས་བོན་ནོ། །བུད་མེད་དང་ནི་སྐྱེས་པའམ། །འདི་ཉིད་ཀུན་ནས་རབ་ཏུ་སྦྱར། །སྡེ་ཚན་བཞི་པའི་བཞི་པ་ནི། །ཐ་མ་བཞི་ནི་རྣམ་སྤངས་པ། །དཀར་དང་ཀུནྡ་ཟླ་བའི་མངོག །ཉི་མའི་ཡི་གེ་རྣམ་པར་ཤེས། །ཐ་མ
ཁྱེད་ཀྱིས་བཟོས་པའི་ཚིག་མཐའི་མངོག   ཅེས་པ་དེ་  མདོག ། ཡིན་པས་དོགས་རྟགས་བཀོད་རོགས།

2018-11-14 22:43 UTC, rekongrabten commented on derge-kangyur-tags/080-tagged.txt
> +[250b.3]དམའ་ན་སྐྱོན་ཆེའོ། །དགྲས་ནི་འཇིགས་པར་འགྱུར་བ་དང་། །འཆི་བར་ཡང་ནི་ཐེ་ཚོམ་མེད། །སྣ་ཞོམ་མིག་ནི་ཡོ་བ་དང་། །རྣ་བ་མཆུ་དང་དབྲལ་བ་ནི། །བགེགས་དང་བདུད་དང་མེས་འཇིགས་ཤིང་། །དངོས་གྲུབ་རིང་བར་འགྱུར་བ་ཉིད། །ག
འདི་ཡང་དཔྲལ་བ་ཡིན་པས་  འདི་ལ་དོགས་རྟགས་བཀོད་རོགས།

2018-11-14 22:43 UTC, rekongrabten commented on derge-kangyur-tags/080-tagged.txt
> +[337a.3]བརྙན་གྱི་ནང་དུ་བཅུག་ནས། མིའི་རུས་པའི་ཕུར་བུ་སོར་གཅིག་པའི་ཚད་དམ། ཡང་ན་ལྕགས་ཀྱི་ཕུར་བུས་བཏབ་ནས། དུར་ཁྲོད་དུ་ས་བརྐོས་ནས་མགོ་ཐུར་དུ་བསྟན་ནས་སྦས་ན། ཞག་བདུན་གྱིས་འཆི་བར་འགྱུར་རོ།། ཨོྃ་ཙཎྜ་མ་ཧཱ་རོ་ཥ
འདིའི་ཚེག་གཉིས་ཁ་བྲལ་རོགས།  སྔགས་ཡིག་གི་བརྗོད་པའི་མཐའི་ཧཱུཾ་དེ་ཧཱུྃ་འདི་ལྟར་བཟོས་ནས་ཚེག་འཇོག་རོགས།

2018-11-15 04:28 UTC, gyamtso59 commented on derge-kangyur-tags/080-tagged.txt
> +[232b.4]ནི། །བརྟན་ཞིང་རྟག་པའི་ས་བོན་ནོ། །བུད་མེད་དང་ནི་སྐྱེས་པའམ། །འདི་ཉིད་ཀུན་ནས་རབ་ཏུ་སྦྱར། །སྡེ་ཚན་བཞི་པའི་བཞི་པ་ནི། །ཐ་མ་བཞི་ནི་རྣམ་སྤངས་པ། །དཀར་དང་ཀུནྡ་ཟླ་བའི་མངོག །ཉི་མའི་ཡི་གེ་རྣམ་པར་ཤེས། །ཐ་མ
མ་དཔེ་ནང་དུ་ཡང་མདོག་རེད། དེ་བས་དོགས་རྟགས་ནང་བཞག་མེད།

2018-11-16 01:36 UTC, rekongrabten approved these changes

2018-11-16 01:36 UTC, merged