2018-12-03
Esukhia/derge-kangyur-old pull request #74
Opened 2018-12-03 11:12 UTC by tseringwa

2018-12-03 12:06 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-03 12:06 UTC, Sangkhar commented on derge-kangyur-tags/084-tagged.txt
> +[104b.6]ཎི་རཏྣེ་སཱ་དྷུ་ཀཱ་ར་པཱུ་ཛ་ས་མ་ཡེ་ཧཱུྃ། ཨོཾ་མ་ཧཱ་མ་ཎི་རཏྣ་དྲྀཥྚ་ཨཱ་ཀརྵ། ཨོཾ་མ་ཎི་རཏྣ་མཱ་ལ་པཱུ་ཛེ། །ཨོཾ་མ་ཎི་རཏྣ་སཱུ་རྱཱ་ལོ་ཀ་པཱུ་ཛེ། ཨོཾ་མ་ཎི་རཏྣ་དྷཱ་ཛ་པཱ་ཏ་ཀ་པཱུ་ཛེ། ཨོཾ་མ་ཎི་རཏྣ་ཨཊྚཱཊྚཱ་ཧཱ་ས
ར་ཞིག་ཆད་འདུག

2018-12-03 12:06 UTC, Sangkhar commented on derge-kangyur-tags/084-tagged.txt
> +[209a.2]གསེར་རམ་དངུལ་གྱི་སྣོད་དག་དང་། །ས་ལས་བྱས་ཀྱང་ཉེས་པ་མེད། །ཡོ་བྱད་ཇི་སྙེད་ཡོད་པ་ཀུན། །དཀྱིལ་འཁོར་དུ་ནི་གཞག་པར་བྱ། །དེ་ལ་ཀོང་བུ་སྟོང་ཕྲག་གམ། །མར་མེ་སྡོང་བུ་ཤིན་ཏུ་འབར། །ཐ་་མེ་སྣོད་གཅིག་སྟེ། །མ་ཚང
ཡི་གེ་བསུབ་འདུག

2018-12-04 04:05 UTC, kungagyaltsen approved these changes

2018-12-04 04:06 UTC, merged