ལས་བྱ། 2018/12/3
Esukhia/derge-kangyur-old pull request #75
Opened 2018-12-03 11:14 UTC by Sermig

2018-12-03 12:01 UTC, Sangkhar requested changes
དོག་རྟགས་ཀྱི་ཚེག་?????

2018-12-03 12:01 UTC, Sangkhar commented on derge-kangyur-tags/015-tagged.txt
> +[227a.5]སྙམ་དུ་སེམས། ལྕེའི་འདུས་ཏེ་རེག་པ་ཡང་གཞན་ལ། སྒྱུ་མ་ཡང་གཞན་ཞིག་ཡིན་སྙམ་མམ། །གསོལ་པ། བཅོམ་ལྡན་འདས་དེ་ལྟ་མ་ལགས་སོ། །བཅོམ་ལྡན་འདས་(གྱིས་‚ཀྱིས)་བཀའ་སྩལ་པ། རབ་འབྱོར་དེ་ཇི་སྙམ་དུ་སེམས། ལུས་ཀྱི་འདུས་
ཡང་དོག་རྟགས་ཀྱི་ཚེག

2018-12-03 12:01 UTC, Sangkhar commented on derge-kangyur-tags/047-tagged.txt
> +[305a.5]ལྟར་འདོད་པ་བཞིན་དུ་བྱང་ཆུབ་ཐོབ་པར་འགྱུར། །མདོ་འདི་བདེ་བར་གཤེགས་པ་རྣམས་ཀྱིས་རབ་བསྔགས་ཤིང་། །བྱང་ཆུབ་སེམས་དཔའ་མང་པོས་ཡོངས་སུ་བཟུང་བ་ཡིན། །དེ་བཞིན་གཤེགས་པ་རྣམས་ཀྱི་སྐུ་ལུས་ནམ་མཁའ་ཡི། །ཁམས་དང་འདྲ
ཡང་ཚེག

2018-12-04 04:23 UTC, kungagyaltsen approved these changes

2018-12-04 04:24 UTC, merged