2018-12-05
Esukhia/derge-kangyur-old pull request #83
Opened 2018-12-05 11:04 UTC by tseringwa

2018-12-05 11:27 UTC, kungagyaltsen requested changes
བསྐྱར་བཟོ་གནང་རོགས།

2018-12-05 11:27 UTC, kungagyaltsen commented on derge-kangyur-tags/005-tagged.txt
> +[62a.5]བྱེད། འགྲོ་བར་བྱེད་ཅིང་ཇི་སྲིད་དུ་ནོམ་པར་མི་བྱེད། ཉུག་པར་མི་བྱེད་པ་དེ་སྲིད་དུ་ཉེས་བྱས་སུ་འགྱུར་རོ། །ནོམ་པར་(བྱད,བྱེད)། ཉུག་པར་བྱེད་ཅིང་ཇི་སྲིད་དུ་གནས་ནས་གནས་སུ་སྦེད་པར་མི་བྱེད་པ་དེ་སྲིད་དུ་ཉེས
[62a.5] འདི་ལ་དོག་རྟགས་མི་དགོས།

2018-12-05 11:27 UTC, kungagyaltsen commented on derge-kangyur-tags/005-tagged.txt
> +[62b.2]བྱེད། ཉུག་པར་བྱེད་ཅིང་ཇི་སྲིད་དུ་གནས་ནས་གནས་སུ་སྦེད་པར་མི་བྱེད་པ་དེ་སྲིད་དུ་ཉེས་པ་སྦོམ་པོར་འགྱུར་རོ། །གནས་ནས་གནས་སུ་སྦེད་པར་བྱེད་ན་བརྐུས་པར་བརྗོད་པར་བྱ་སྟེ། (རིང,རིན་)ཐང་བརྩི་བར་བྱ་ཞིང་དངོས་པོ
[62b.2] མ་དཔེ་བཞིན། རིང་ཐང་ ཟེར་ནས་བཟོ་རོགས་གནང།

2018-12-05 11:27 UTC, kungagyaltsen commented on derge-kangyur-tags/005-tagged.txt
> +[72b.3]པས་ཕམ་པར་བྱས་ན་ཉེས་པ་(སྦོར,སྦོམ་)པོར་འགྱུར་རོ། །གལ་ཏེ་དགེ་སློང་གིས་ཁྱིམ་པ་ཕམ་པར་བྱས་ན་དགེ་སློང་དག་རྒྱལ་པོ་ནི་རྩོད་པ་ཐམས་ཅད་ཀྱི་དཔོན་པོ་ཡིན་པས་བརྐུས་པར་བརྗོད་པར་བྱ་སྟེ། རིན་ཐང་བརྩི་བར་བྱ་ཞིང་དང
[72b.3] དོག་རྟགས་མ་བཞག་ནས་ སྦོམ་པོར་ཟེར་ནས་འབྲི་རོགས།

2018-12-06 04:24 UTC, Sangkhar approved these changes

2018-12-06 04:24 UTC, merged