གཟའ་ཕུར་བུའི་ལས་ཀ2018.12.6
Esukhia/derge-kangyur-old pull request #91
Opened 2018-12-06 11:25 UTC by gyamtso59

2018-12-06 12:06 UTC, Sangkhar requested changes
བར་སྟོང་བཟོ་ཡ་གཅིག་འདུག

2018-12-06 12:40 UTC, kungagyaltsen requested changes

2018-12-06 12:40 UTC, kungagyaltsen commented on derge-kangyur-tags/091-tagged.txt
> +[46a.4]དྷརྨ་ས་ཏྱེ་ན། སཾ་གྷ་ས་ཏྱེ་ན། ས་ཏྱ་བཱ་དི་ནཱཾ། ས་ཏྱེ་ན། བུདྡྷ་ས་ཏྱེ་མཱ་ཏི་ཀྲ་མ། དྷརྨ་ས་ཏྱེ་མཱ་ཏི་ཀྲ་མ། སཾ་གྷ་ས་ཏྱེ་མཱ་ཏི་ཀྲ་མ། ས་ཏྱེ་བཱ་དི་ནཱཾ། ས་ཏྱེ་མཱ་ཏི་ཀྲ་མ། ལམྦོད་རི། ལམྦོ་ད་རི། ཀུ་ཊ་ཀུ་ཊ།
[46a.4] ཀུནྚ་གུཊྚ  ན་གསུབ་ནས་ཚབ་ལ་ཊ་འདི་ཞོག།

2018-12-07 04:49 UTC, kungagyaltsen approved these changes

2018-12-07 04:49 UTC, merged